name: Scraping and Upload to Google Drive

on:
  # Trigger terjadwal (setiap hari pukul 10:00 UTC atau 17:30 WIB)
  schedule:
    - cron: '30 10 * * *'  # Format cron: menit jam hari bulan hari-minggu

  # Trigger manual dari GitHub Actions UI
  workflow_dispatch:

jobs:
  scrape-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Sesuaikan dengan versi Python yang Anda gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Pastikan Anda memiliki file requirements.txt

    - name: Set up Google Cloud credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Mengambil credential dari GitHub Secrets
      run: |
        echo "$GOOGLE_CREDENTIALS" > credential.json  # Menyimpan credential ke file credential.json

    - name: Run scraping script
      run: |
        python scraping.py  # Ganti dengan nama file script Anda

    - name: Install Google Drive API dependencies
      run: |
        pip install google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Upload files to Google Drive
      run: |
        python upload_to_drive.py  # Script untuk mengunggah file ke Google Drive