name: Scraping and Save to Google Spreadsheet

on:
  # Trigger terjadwal (setiap hari pukul 00:00 UTC)
  schedule:
    - cron: '0 0 * * *'  # Format cron: menit jam hari bulan hari-minggu

  # Trigger manual dari GitHub Actions UI
  workflow_dispatch:

jobs:
  scrape-and-save:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Sesuaikan dengan versi Python yang Anda gunakan

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Pastikan Anda memiliki file requirements.txt

    - name: Set up Google Cloud credentials
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}  # Mengambil credential dari GitHub Secrets
      run: |
        echo "$GOOGLE_CREDENTIALS" > credential.json  # Menyimpan credential ke file credential.json

    - name: Run scraping script
      run: |
        python scraping.py

    - name: Install Google Sheets API dependencies
      run: |
        pip install gspread google-auth

    - name: Save data to Google Spreadsheet
      run: |
        python save_to_spreadsheet.py  # Script untuk menyimpan data ke Google Spreadsheet